apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-sender
spec:
  replicas: 0
  selector:
    matchLabels:
      component: sender
      app: maestro
  template:
    metadata:
      labels:
        component: sender
        app: maestro
    spec:
      strategy:
        type: Recreate
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - maestroperf
      initContainers:
        - name: copyconfig
          image: centos:7
          command:
            - /bin/bash
            - -c
            - cp /config/* /opt/maestro/maestro-worker/config/ && echo maestro.worker.host=$HOSTNAME >> /opt/maestro/maestro-worker/config/maestro-worker.properties
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config
              mountPath: /config
            - mountPath: /opt/maestro/maestro-worker/config
              name: config-store
      containers:
        - name: sender
          image: maestroperf/maestro-sender:1.5.0-SNAPSHOT
          command:
            - /bin/bash
            - -c
            - echo maestro.worker.host=$HOSTNAME >> /opt/maestro/maestro-worker/config/maestro-worker.properties && /usr/bin/maestro-container-wrapper
          env:
            - name: MAESTRO_BROKER
              value: mqtt://broker
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - mountPath: /opt/maestro/maestro-worker/config
              name: config-store
            - mountPath: /maestro
              name: data
      volumes:
        - name: data
          emptyDir: {}
        - name: config-store
          emptyDir: {}
        - name: config
          configMap:
            name: sender-config
